In [1]:
import numpy

In [4]:
db=[["vimal",1111,"v@lw.com"],["Himanshu",2222,"hdogra@redhat.com"],["Eric",3333,"eric@redhat.com"]]

In [25]:
db

[['vimal', 1111, 'v@lw.com'],
 ['Himanshu', 2222, 'hdogra@redhat.com'],
 ['Eric', 3333, 'eric@redhat.com']]

In [26]:
type(db)

list

In [8]:
a=numpy.array(db)

In [9]:
type(a)

numpy.ndarray

In [10]:
a

array([['vimal', '1111', 'v@lw.com'],
       ['Himanshu', '2222', 'hdogra@redhat.com'],
       ['Eric', '3333', 'eric@redhat.com']], dtype='<U17')

In [22]:
a[1:,1]

array(['2222', '3333'], dtype='<U17')

In [21]:
a.dtype

dtype('<U17')

In [27]:
a.shape

(3, 3)

In [45]:
a

array([['vimal', '1111', 'v@lw.com'],
       ['Himanshu', '2222', 'hdogra@redhat.com'],
       ['Eric', '3333', 'eric@redhat.com']], dtype='<U17')

In [29]:
number=a[:,1]

In [30]:
number

array(['1111', '2222', '3333'], dtype='<U17')

In [44]:
number.dtype

dtype('<U17')

In [40]:
n=number.astype(int)

In [41]:
n

array([1111, 2222, 3333])

In [43]:
n.dtype

dtype('int64')

In [48]:
n.max()

3333

In [49]:
a

array([['vimal', '1111', 'v@lw.com'],
       ['Himanshu', '2222', 'hdogra@redhat.com'],
       ['Eric', '3333', 'eric@redhat.com']], dtype='<U17')

In [59]:
a.dtype= {'names': ['StudentName','Phone','Email'], 'formats': [numpy.str, numpy.int32, numpy.str]}                                                         

In [61]:
t=numpy.array([1,2,3])

In [62]:
t

array([1, 2, 3])

In [67]:
t.dtype={'names': ['ID'], 'formats': [numpy.int32]}

In [68]:
t

array([(1,), (0,), (2,), (0,), (3,), (0,)], dtype=[('ID', '<i4')])

In [69]:
t['ID']

array([1, 0, 2, 0, 3, 0], dtype=int32)