In [6]:
str="Himanshu Dogra How are you!!"

In [7]:
type(str)

str

In [8]:
str[0::3]

'HahDrH eo!'

In [9]:
"you" in str

True

In [10]:
y="the mission of iiec is right education."

In [12]:
("missing" in y) or ("right" in y)

True

In [13]:
import pyttsx3

In [1]:
help(break)

SyntaxError: invalid syntax (<ipython-input-1-7619105823a9>, line 1)

In [1]:
dic={'fruit_name':('apple','mango','banana','guava')}

In [2]:
type(dic)

dict

In [3]:
dic

{'fruit_name': ('apple', 'mango', 'banana', 'guava')}

In [5]:
dic.keys()

dict_keys(['fruit_name'])

In [6]:
dic.values()

dict_values([('apple', 'mango', 'banana', 'guava')])

In [ ]:
#class in python are like blueprints and then you have to create objects from it.

In [19]:
class human:
    name=None
    age=None
    def get_name(self):
        print("Enter your name: ")
        self.name=input()
    def get_age(self):
        print("Enter your age:")
        self.age=input()
    def put_name(self):
        print("Your name is:",self.name)
    def put_age(self):
        print("your age is:",self.age)





In [20]:
person1=human()

In [21]:
person1.get_name()

Enter your name: 
hi


In [22]:
person1.get_age()

Enter your age:
38


In [23]:
person1.put_name()

Your name is: hi


In [24]:
person1.put_age()

your age is: 38


In [31]:
person1.put_name(),person1.put_age()

Your name is: hi
your age is: 38


(None, None)

In [ ]:
#__init__ constructor

In [28]:
class student:
    def __init__(self,name,age,branch):
        self.name=name
        self.age=age
        self.branch=branch
    def print_student(self):
        print("name:",self.name)
        print("age:",self.age)
        print("branch:",self.branch)

In [29]:
student1=student("bob",28,"engineering")

In [30]:
student1.print_student()

name: bob
age: 28
branch: engineering


In [ ]:
#single level inheritence 

In [34]:
class fruit:
    def __init__(self):
        print("I am a fruit.")
class citrus(fruit):
    def __init__(self):
        print("I am citrus.")
        super().__init__()
Lemon=citrus()

I am citrus.
I am a fruit.


In [35]:
Lemon

In [36]:
print(Lemon)

In [37]:
type(Lemon)

__main__.citrus

In [38]:
#Numpy Array

In [39]:
import numpy as np

In [40]:
a=np.array([1,2,3])

In [41]:
a

array([1, 2, 3])

In [42]:
b=np.array([[1,2,3],[4,5,6]])

In [43]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#zero numpy array

In [46]:
import numpy as np
a=np.zeros((5,5))

In [47]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Numpy array sum operations

In [53]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

a+b
np.sum((a,b),axis=1)

array([ 6, 15])

In [54]:
#numpy array of first two largest values


In [59]:
import numpy as np

x=np.array([2,3,45,65,100,98])

x[np.argsort(x)[-2:][::-1]]

array([100,  98])

In [60]:
#Creating a DF into list and dic

In [62]:
import pandas as pd

l1=[1,2,3,4,5]

data1=pd.DataFrame(l1)

data1

0
0  1
1  2
2  3
3  4
4  5

In [67]:
dic1={'fruit_name':['apple','mango','banana'],'count':(12,24,36)}
pd.DataFrame(dic1)

fruit_name  count
0      apple     12
1      mango     24
2     banana     36

In [68]:
#from a dataset, extract some datafields. 

In [85]:
import pandas as pd

iris=pd.read_csv("iris.csv")

In [86]:
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [88]:
iris[(iris['Sepal.Length']>5) & (iris["Sepal.Width"]>3)]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa

In [89]:
#replace some data fields from the dataset

In [96]:
import pandas as pd
import numpy as np

iris=pd.read_csv("iris.csv")

iris1=iris

iris.iloc[0:3,1:3]=np.NAN

In [97]:
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          NaN           NaN          0.2  setosa
2           4.7          NaN           NaN          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [99]:
iris1

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          NaN           NaN          0.2  setosa
2           4.7          NaN           NaN          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [100]:
#counting NaN  values in a column of a dataframe

In [121]:
import pandas as pd


csv=pd.read_csv('nhanes.csv')

csv.isna().sum()

age    0
bmi    3
hyp    2
chl    2
dtype: int64

In [ ]:
#how to open and read a file in python

In [118]:
f=open("/Users/hdogra/test","r")

In [120]:
f.read()

'[\n34,\n45,\n56,\n]\n'

In [124]:
def f(x,l=[]):
    for i in range(x):
        l.append(i*i)
    print(l) 

f(2)
f(3,[3,2,1])
f(3)

[0, 1]
[3, 2, 1, 0, 1, 4]
[0, 1, 0, 1, 4]


In [122]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [123]:
range(2)

range(0, 2)

In [125]:
my_string="foo ba"

In [126]:
k=[(i.upper(),len(i)) for i in my_string]

In [127]:
print(k)

[('F', 1), ('O', 1), ('O', 1), (' ', 1), ('B', 1), ('A', 1)]


In [133]:
for i in my_string:
    k=[(i.upper(),len(i))]
    print(k)

[('F', 1)]
[('O', 1)]
[('O', 1)]
[(' ', 1)]
[('B', 1)]
[('A', 1)]


In [136]:
name="Himanshu"

for i in range(1,5):
    print(i)

1
2
3
4


In [138]:
for i in range(2,10,2):
    print(i)

2
4
6
8


In [143]:
letters="PTJB"

for letter in letters:
    print(letter+name[1:])

Pimanshu
Timanshu
Jimanshu
Bimanshu


In [147]:
def hello():
    name=input("Enter Your Name: ")
    print("Hello " + name)

In [148]:
hello()

Enter Your Name: Himanshu
Hello Himanshu


In [176]:
numbers=[2,3,4,5,6,10,12,25,54]

even=[]

for number in numbers:
    if number % 2 == 0:

        even.append(number)
    else:
        continue

print(even)

[2, 4, 6, 10, 12, 54]


In [160]:
for row in range(5):
    for col in range(5):
        print(col,end='')
    print()
   

01234
01234
01234
01234
01234


In [166]:
from math import *
print(ceil(36.1))

37


In [177]:
friends=["Himanshu","vimal","monika","swati","shweta"]

friends.insert(0,"jack")
friends

['jack', 'Himanshu', 'vimal', 'monika', 'swati', 'shweta']

In [181]:
friends
#friends.remove("vimal")
friends

['jack', 'Himanshu', 'monika', 'swati', 'shweta']

In [184]:
friends.clear()
friends

[]

In [186]:
friends=["Himanshu","vimal","monika","swati","shweta"]

friends.pop()
friends

['Himanshu', 'vimal', 'monika', 'swati']

In [191]:
print(friends.index("monika"))

2


In [194]:
print(friends.count("vimal"))

1


In [230]:
from math import *

numbers=[2,3,4,5,2,58,10,10,2,4,5,4,6,7,3,2]

numbers.sort()
print(numbers)

count=[]

for i in numbers:
    count.append(numbers.count(i))
    


print(count)

    

[2, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 7, 10, 10, 58]
[4, 4, 4, 4, 2, 2, 3, 3, 3, 2, 2, 1, 1, 2, 2, 1]


In [222]:
numbers=[4, 2, 3, 2, 4, 1, 2, 2, 4, 3, 2, 3, 1, 1, 2, 4]
numbers.sort()
print(numbers)

[1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4]


In [12]:
import re

with open('/Users/hdogra/test') as fh:
    fstring=fh.readlines()

pattern=re.compile(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})')

ip_list=[]

for i in fstring:
    ip_list.append(pattern.search(i)[0])
    
ip_list.sort()

print(ip_list,"")

from collections import Counter

def most_frequent(ip_list):
    most=[word for word, word_count in Counter(ip_list).most_common(5)]
    print (most)

most_frequent(ip_list)

['80.91.33.133', '93.180.71.3', '217.168.17.5', '173.203.139.108', '188.138.60.101']
