In [6]:
str="Himanshu Dogra How are you!!"

In [7]:
type(str)

str

In [8]:
str[0::3]

'HahDrH eo!'

In [9]:
"you" in str

True

In [10]:
y="the mission of iiec is right education."

In [12]:
("missing" in y) or ("right" in y)

True

In [13]:
import pyttsx3

In [1]:
help(break)

SyntaxError: invalid syntax (<ipython-input-1-7619105823a9>, line 1)

In [1]:
dic={'fruit_name':('apple','mango','banana','guava')}

In [2]:
type(dic)

dict

In [3]:
dic

{'fruit_name': ('apple', 'mango', 'banana', 'guava')}

In [5]:
dic.keys()

dict_keys(['fruit_name'])

In [6]:
dic.values()

dict_values([('apple', 'mango', 'banana', 'guava')])

In [ ]:
#class in python are like blueprints and then you have to create objects from it.

In [19]:
class human:
    name=None
    age=None
    def get_name(self):
        print("Enter your name: ")
        self.name=input()
    def get_age(self):
        print("Enter your age:")
        self.age=input()
    def put_name(self):
        print("Your name is:",self.name)
    def put_age(self):
        print("your age is:",self.age)





In [20]:
person1=human()

In [21]:
person1.get_name()

Enter your name: 
hi


In [22]:
person1.get_age()

Enter your age:
38


In [23]:
person1.put_name()

Your name is: hi


In [24]:
person1.put_age()

your age is: 38


In [31]:
person1.put_name(),person1.put_age()

Your name is: hi
your age is: 38


(None, None)

In [ ]:
#__init__ constructor

In [28]:
class student:
    def __init__(self,name,age,branch):
        self.name=name
        self.age=age
        self.branch=branch
    def print_student(self):
        print("name:",self.name)
        print("age:",self.age)
        print("branch:",self.branch)

In [29]:
student1=student("bob",28,"engineering")

In [30]:
student1.print_student()

name: bob
age: 28
branch: engineering


In [ ]:
#single level inheritence 

In [34]:
class fruit:
    def __init__(self):
        print("I am a fruit.")
class citrus(fruit):
    def __init__(self):
        print("I am citrus.")
        super().__init__()
Lemon=citrus()

I am citrus.
I am a fruit.


In [35]:
Lemon

In [36]:
print(Lemon)

In [37]:
type(Lemon)

__main__.citrus

In [38]:
#Numpy Array

In [39]:
import numpy as np

In [40]:
a=np.array([1,2,3])

In [41]:
a

array([1, 2, 3])

In [42]:
b=np.array([[1,2,3],[4,5,6]])

In [43]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#zero numpy array

In [46]:
import numpy as np
a=np.zeros((5,5))

In [47]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Numpy array sum operations

In [53]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

a+b
np.sum((a,b),axis=1)

array([ 6, 15])

In [54]:
#numpy array of first two largest values


In [59]:
import numpy as np

x=np.array([2,3,45,65,100,98])

x[np.argsort(x)[-2:][::-1]]

array([100,  98])